### PR TITLE
Trying a thing

### PR DESCRIPTION
**Pull request by LeticiaBriscoe**
I cant make this work

### CODE REVIEW

**Comment by aliblackwell** [comment]
@Kellyana what are your blockers?

**Comment by Johntwity** [comment]
@johntwity  @aliblackwell Your Arduino coding was awesome stop being down on yourself.

**Comment by Johntwity** [comment]
Your coding was great , your best thats going Kellyanna.

**Comment by LeticiaBriscoe** [comment]
Thank you Johntwity, your comments are very encouraging.

**Comment by LeticiaBriscoe** [comment]
I want it to blink once at start up, not in a loop

**Comment by aliblackwell** [comment]
Well done @Kellyana this is great.

**Pull request merged**
